### ISSUE TITLE
Is this same as Mustachio in Postmark?

### ISSUE THREAD

**Issue by leopangchan** [maghoff/mustachio#21]
Mustachio in Postmark (ref: https://postmarkapp.com/blog/why-were-nuts-about-mustachio) has added {{#each}}, but the parser of this npm package couldn't handle it. Please clarify.

Node version: v12.13.1
package.json:
```
{
  "name": "mustachio-node",
  "version": "1.0.0",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "mustachio": "1.0.0"
  },
  "devDependencies": {},
  "description": ""
}
```

![image](https://user-images.githubusercontent.com/16515271/127375068-8b85db5d-ffbf-4593-9cec-e06df3b6d757.png)

**Comment by maghoff** [comment]
This package is unrelated to Postmark, it is just a naming collision.
